// Generated by gencpp from file mrsim/rodom.msg
// DO NOT EDIT!


#ifndef MRSIM_MESSAGE_RODOM_H
#define MRSIM_MESSAGE_RODOM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrsim
{
template <class ContainerAllocator>
struct rodom_
{
  typedef rodom_<ContainerAllocator> Type;

  rodom_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  rodom_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::mrsim::rodom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrsim::rodom_<ContainerAllocator> const> ConstPtr;

}; // struct rodom_

typedef ::mrsim::rodom_<std::allocator<void> > rodom;

typedef boost::shared_ptr< ::mrsim::rodom > rodomPtr;
typedef boost::shared_ptr< ::mrsim::rodom const> rodomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrsim::rodom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrsim::rodom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mrsim::rodom_<ContainerAllocator1> & lhs, const ::mrsim::rodom_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mrsim::rodom_<ContainerAllocator1> & lhs, const ::mrsim::rodom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mrsim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mrsim::rodom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrsim::rodom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrsim::rodom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrsim::rodom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrsim::rodom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrsim::rodom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrsim::rodom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const ::mrsim::rodom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938fa65709584ad8ULL;
  static const uint64_t static_value2 = 0xe77d238529be13b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrsim::rodom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrsim/rodom";
  }

  static const char* value(const ::mrsim::rodom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrsim::rodom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::mrsim::rodom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrsim::rodom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rodom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrsim::rodom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrsim::rodom_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRSIM_MESSAGE_RODOM_H
